### ISSUE TITLE
Using `yield` hangs IDE

### ISSUE THREAD

**Issue by dungwinux** [ocelot-ide/Ocelot#142]
### Version

```js
{
  elementaryJS: "c122f37",
  ocelot: "6887ff2"
}
```

### Problem
When explicitly using `yield` in a generator function, ElementaryJS detects this as SyntaxError (`SyntaxError: Unexpected strict mode reserved word`). However, Ocelot hangs due to the error being uncaught. 

Interestingly, using `yield` in an _anonymous_ generator function works fine, and ElementaryJS doesn't detect as error.

### Step to reproduce

1. Input the below javascript code:

```js
function* generator() {
    yield 1;
    yield 2;
}
const range = generator();
```

#### Expected behavior

Print error in Ocelot console

#### Actual behavior

Ocelot IDE hangs. In developer console, it prints out error as below:

![image](https://user-images.githubusercontent.com/23451424/108254574-c71fa780-718d-11eb-9116-5325d8b82a20.png)

**Comment by arjunguha** [comment]
Closing, same as the other error.
