### ISSUE TITLE
Spreading array hangs IDE

### ISSUE THREAD

**Issue by dungwinux** [ocelot-ide/Ocelot#143]
This issue is related to https://github.com/ocelot-ide/ElementaryJS/issues/200

### Problem
While ElementaryJS detects this as an error, Ocelot hangs due to the error being uncaught. 

### Step to reproduce

1. Input the below javascript code:

```js
[...[1, 2]].length
```

#### Expected behavior

No error

#### Actual behavior

Ocelot IDE hangs. In developer console, it prints out error as below:

![image](https://user-images.githubusercontent.com/23451424/108255218-8c6a3f00-718e-11eb-9e43-ce1ecd128bc8.png)

**Comment by arjunguha** [comment]
This is fixed by https://github.com/ocelot-ide/Stopify/commit/10d6aa23f434ccfa539226d39a24bbd44ac8ed60

It will be in the next deployment of Ocelot.
