### ISSUE TITLE
invalid function hangs IDE

### ISSUE THREAD

**Issue by mminea** [ocelot-ide/Ocelot#145]
function f(x, x) {  }
will hang the IDE on clicking 'Run'.
Pressing 'Stop' will gray out Run/Test buttons, so a reload is needed (this seems to be common behavior).
Thanks for looking into this.

**Comment by arjunguha** [comment]
This is getting addressed: https://github.com/ocelot-ide/Stopify/pull/486

**Comment by arjunguha** [comment]
This is fixed. Closing the issue. The next deployment of the IDE will not have this problem.
