### ISSUE TITLE
Local Ocelot version?

### ISSUE THREAD

**Issue by bardo84** [ocelot-ide/Ocelot#167]
I like the front end with the resizable panes which can be turned off as well but would like to use them 
- without any cloud intelligence, less functionality ok
- no restricted JS subset. 
- drawing redirected to drawing pane
- REPL in console

Would look almost like the Matlab GUI - Any suggestions?

**Comment by arjunguha** [comment]
I'm sure this could be done, go for it. :)

**Comment by bardo84** [comment]
Definitively!
I was looking in the source for a skeleton code where the panes are defined, but could not find it.
Is this code in or kept elsewhere?
I have coding experience but not much exposure to html.
Thanks for a guiding hand, if possible!
